[package]
name = "mandelbrot"
version = "0.1.0"
edition = "2021"

[dependencies]
num = "0.4.0"
image = "0.23.14"
rayon = "1.10.0"
wgpu = "22.1.0"
pollster = "0.3.0"
bytemuck = "1.16.3"
flume = "0.11.0"